name: test-recorder

services:
  test-recorder-backend:
    build:
      context: ./scenario-back
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: jdbc:sqlite:/data/test_recorder_scenario_db.db
      SESSION_COOKIE_SECURE: "false"
    volumes:
      - ./data:/data
    expose:
      - "6667"
    restart: unless-stopped

  test-recorder-frontend:
    build:
      context: ./scenario-db-ui
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    depends_on:
      - test-recorder-backend
    restart: unless-stopped
